### ISSUE TITLE
Make useTitle return title

### ISSUE THREAD

**Issue by talentlessguy** [Gladear/haunted-router#2]
It would be logical to have `title` as a primary value, like this:

```js
const [title, setTitle] = useTitle()

return html`<p>${title}</p>`
```

**Comment by Gladear** [comment]
Hello, thanks for giving feedback :blush:

Do you have a use case for this feature ? I don't really see what this could be used for.

Maybe you want to change the title dynamically depending on the state of the page ? I'm not sure this is very common. As a workaround, you could do something like that:
```js
const [title, setTitle] = useState("whatever");
useTitle(title);

return html`<p>${title}</p>`;
```

**Comment by talentlessguy** [comment]
@Gladear okay, thanks for the tip

in fact I can just use `document.title`
