### ISSUE TITLE
Problem with useSearchParams

### ISSUE THREAD

**Issue by Mateozmaldonado17** [Gladear/haunted-router#6]
When try use that hook, VS show to me that

Module '"../../../node_modules/haunted-router/haunted-router"' has no exported member 'useSearchParams'

**Comment by Gladear** [comment]
Sorry for the late reply, I've been quite busy lately !

Indeed, it looks like I forgot to update TypeScript definitions, I'll do that right away.

**Comment by Gladear** [comment]
Fixed with 0.2.1 :slightly_smiling_face:
